version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lavafacil_app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - db

  web:
    image: nginx:alpine
    container_name: lavafacil_web
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: postgres:15
    container_name: lavafacil_db
    environment:
      POSTGRES_DB: lavafacil
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
